### ISSUE TITLE
how to disable pastel colors

### ISSUE THREAD

**Issue by MyNameIsTroll** [vikgor/portfolio#2]
Hi, 
First of all, thank you for the theme I'm currently using, I think it's great.
I wanted to ask you if there was a way to disable random pastel colors in the gallery because I use png images and it produces an unwanted effect in my case.

**Comment by MyNameIsTroll** [comment]
I have just found it by myself and I indicate it here for those who would like to do like me. Just open the file "home.php", in the part  and delete the php // random pastel color.

**Comment by vikgor** [comment]
Hey,
Thank you for checking it out!
I've updated the theme, now it only sets a background color if there is no cover image.

But you're right, you can easily delete the style element in _home.php_
`style="background-color:<?php echo $rand_background; ?>`

Closing it now since it's resolved
