### ISSUE TITLE
Finding a feature

### ISSUE THREAD

**Issue by mymurkas** [vikgor/portfolio#3]
Hi and thanks for a good theme!
On the feature list a read"Jetpack gallery with carousel feature" But I cant find how you get this to work on the images? And how to create a gallery?
Thank you!
---
Ok I get it now. I thought I could get a jetpack gallery also within one page. Would that be possible somehow? Would be great if it could. Uploading images on a page and insert them and they were put into a grid + the carousel feature when clicked on.

**Comment by mymurkas** [comment]
Hello again! Have you seen this? I'd like to extend your theme so that it is possible to make a Jetpack tiled gallery also on a single page with all the images uploaded to it. Will check it out but would be glad for any help! 
You also write that there is the carusel feature, but how do I get this to work?
Thanks alot!
m.

**Comment by vikgor** [comment]
Hey, sorry for the late response
The jetpack gallery is included and possible to implement, however I couldn't find an easy way to make the gallery (there must be a plugin that helps with that).
I managed to insert Jetpack galleries with a HTML code inserted into source code (I'm using TinyMCE and it lets me do that)

```html
<div class="gallery gallery-columns-3 gallery-size-medium" data-carousel-extra="{&quot;blog_id&quot;:,&quot;permalink&quot;:&quot;}">
    <figure class="gallery-item">
        <div class="gallery-icon landscape">
            <a href="">
                <img 
                     class="attachment-medium size-medium" 
                     src="" 
                     alt="Alternative description" 
                     data-attachment-id="1" 
                     data-permalink="" 
                     data-orig-file="" 
                     data-orig-size="2880,1920" 
                     data-image-title="Image title" 
                     data-image-description="Image description" 
                     data-medium-file="" 
                     data-large-file=""
                     >
            </a>
        </div>
    </figure>
    
    <!-- 
    <figure class="gallery-item">

    Another image in here. Change the id on each <figure> item

    </figure>
    -->

</div>
```

The html style is for a better showcase, obviously
This is a temporary solution, but works quite well
Hope this helps

**Comment by mymurkas** [comment]
Thank you! I'll give it a try.
